### ISSUE TITLE
Error Too Many Values to Unpack

### ISSUE THREAD

**Issue by zach-is-my-name** [github-tooling/ghtopdep#22]
```
[~/Github]$ ghtopdep --table --minstar 50 --rows 50 https://github.com/chalk/ansi-regex/
Traceback (most recent call last):
  File "/home/zmg/.local/bin/ghtopdep", line 8, in <module>
    sys.exit(cli())
  File "/home/zmg/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/zmg/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/zmg/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zmg/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/zmg/.local/lib/python3.10/site-packages/ghtopdep/ghtopdep.py", line 145, in cli
    owner, repository = urlparse(url).path[1:].split("/")
ValueError: too many values to unpack (expected 2)
```

**Comment by zach-is-my-name** [comment]
The trailing slash in the url did it.
