### ISSUE TITLE
urllib3.exceptions.InvalidHeader: Invalid Retry-After header: 1m0s on some repos

### ISSUE THREAD

**Issue by evmorov** [github-tooling/ghtopdep#9]
```
ghtopdep https://github.com/activeadmin/inherited_resources
```

gives me

```
Traceback (most recent call last):itories
⠸ Fetching information about repositories  File "/usr/local/bin/ghtopdep", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/ghtopdep/ghtopdep.py", line 156, in cli
    response = sess.get(page_url)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cachecontrol/adapter.py", line 53, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 831, in urlopen
    retries.sleep(response)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 299, in sleep
    slept = self.sleep_for_retry(response)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 276, in sleep_for_retry
    retry_after = self.get_retry_after(response)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 273, in get_retry_after
    return self.parse_retry_after(retry_after)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 256, in parse_retry_after
    raise InvalidHeader("Invalid Retry-After header: %s" % retry_after)
urllib3.exceptions.InvalidHeader: Invalid Retry-After header: 1m0s
```

I have a token added. Can use `--description` on other repos:

```
ghtopdep --description https://github.com/trailblazer/trailblazer-rails

| url                                                              |   stars | description                                                |
|------------------------------------------------------------------|---------|------------------------------------------------------------|
| https://github.com/matestack/matestack-ui-core                   |     217 | A modern View Layer for Rails built on Trailblazer and...  |
| https://github.com/crowdAI/crowdai                               |     143 | Fighting for Open Science with Open Data                   |
| https://github.com/apotonick/gemgem-trbrb                        |     131 | The Trailblazer book's example app.                        |
| https://github.com/etalab/sirene_as_api                          |      47 | Une API pour le fichier sirene                             |
| https://github.com/AIcrowd/AIcrowd                               |      31 | Crowd Sourcing Artificial Intelligence to solve Real...    |
| https://github.com/symbiod/symbiod                               |      21 | :factory: A place where non-profits and developers meet... |
| https://github.com/danielres/react-redux-rails-oauth-boilerplate |      17 | An experimental boilerplate with decoupled...              |
| https://github.com/sergey-koba-mobidev/boxroom-engine            |      12 | Boxroom web file manager Rails engine                      |
| https://github.com/v-kolesnikov/emilito                          |      10 | :gem: Emilito                                              |
| https://github.com/apotonick/trb-cart                            |       9 | Shopping cart app with Trailblazer.                        |
found 311 repositories others repositories are private
found 74 repositories with more than zero star
```

```
echo $GHTOPDEP_TOKEN
3d8xxxxaab214161yyyyyyy27yyyy180xxxxx81
```

Env:

- macOS 10.15.3
- pip installed with brew

```
pip3 show ghtopdep

Name: ghtopdep
Version: 0.3.9
Summary: CLI tool for sorting dependents repositories and packages by stars
Home-page: None
Author: Andriy Orehov
Author-email: andriyorehov@gmail.com
License: MIT
Location: /usr/local/lib/python3.7/site-packages
Requires: appdirs, click, lockfile, selectolax, pipdate, requests, tabulate, github3.py, cachecontrol, halo
Required-by:
```

**Comment by evmorov** [comment]
```
ghtopdep https://github.com/thoughtbot/shoulda-matchers
```

gives the same error.

**Comment by andriyor** [comment]
Related Issue https://github.com/urllib3/urllib3/issues/1822

**Comment by andriyor** [comment]
Seems like GitHub already fixed it
Can you confirm it?

Because of scraping popular project, such this takes a long time I added flag --report that will send results of scraping to lambda on AWS https://github.com/github-tooling/ghtopdep-backend and put to MongoDB collection with TTL seted to one month
Also, I created a tiny frontend for that
Source: https://github.com/github-tooling/ghtopdep-frontend-react
Site: https://ghtopdep.now.sh/
So with the flag --report  cli will send scraped data. If it doesn't exist on mongo and receive if it already exists

**Comment by evmorov** [comment]
It's fixed. Thanks @andriyor
